### PR TITLE
Fixing issue #34, naming validation and general refactoring on the bicep codebase (new region deployment)

### PR DESCRIPTION
**Pull request by nianton**
Included naming module to validate names, included tagging mechanism, refactored a few files to consolidate required parameters, parameterized the numeric suffix, minor changes to support optionally creating the subnet for CICD agent, modularize private DNS zone creation and related VNET links and A records, parameterized setting availability zone for created VMs.

### CODE REVIEW

**Comment by nianton** [comment]
Finally, all checks were successful (there are a couple of minor issues we should probably take care on the CI/CD process). Please note I had to switch the configured region to be EastUS for the deployment to go through and delete existing deployments from WestUS2.

**Review by torokzs — APPROVED** [review]
Thank you Nikos, looks great!

**Comment by petemessina** [comment]
@nianton I had a few questions, but nothing major.

**Comment by cykreng** [comment]
@petemessina did you have a chance to connect with @nianton ?

**Review by nabeelp — APPROVED** [review]

**Comment by nabeelp** [comment]
closes #34

**Pull request merged**
