### PR TITLE
Adding in sample tests for tests for resources

### PR DESCRIPTION
**Pull request by petemessina**
I added some samples for testing to make sure we are on the right track on what to test.

### CODE REVIEW

**Review by torokzs — COMMENTED** [review]
Good sample tests for created resources, would be great to integrate to our workflow. However we should test that sample app is up and running with one some functional tests as well.

**Comment by petemessina** [comment]
@torokzs The only concern I have is running tests against the service we would need to have them execute on the build server since the only way to access the sample app would be to be inside the vnet correct?

**Comment by torokzs** [comment]
Yes, you are right!

**Comment by petemessina** [comment]
@torokzs based on that I don't think smoke testing should be a part of this test set and we should ensure structure and properties. Thats why I left it out for now and we can decide if smoke testing makes sense for the accelerator in a different test set or we leave that out.

**Pull request merged**
