### PR TITLE
Adding redis as an option

### PR DESCRIPTION
**Pull request by robertopc1**

### CODE REVIEW

**Comment by torokzs** [comment]
Thank you @robertopc1! Would be great extend AzureBicepDeploy workflow with createAcreResource parameter + the doc with all the added services. The sample app deployed through deploysampleapp workflow.

**Comment by torokzs** [comment]
> Got it @torokzs, I'm creating a new commit with the changes. I already updated the AzureBicepDeploy to include the new parameters for ACRE and updated the document to add the link to the Microsoft docs that talks about ACRE. I don't see the deploy sample app workflow so I'm assuming I will have to create one. Correct?

No, it's here, called deploysampleapp.yml.

**Comment by torokzs** [comment]
> @torokzs Looking at the history I see that the file was added and deleted in April 8th. Would you add the file to this branch, make sure the app deploys correctly and then I can come back adding the required things for Redis? Thank you!

@whsalazar could you add the latest version to this branch, please?

**Comment by cenkms** [comment]
hi @torokzs , looks really well, I will merge this now.

**Pull request merged**
